apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
{{- toYaml .values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{- toYaml .values.labels | nindent 6 }}
  template:
    metadata:
      labels:
{{- toYaml .values.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.containerPort }}