apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-role
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: "{{ .Values.name }}-role-binding"
    namespace: "{{ .Values.namespace }}"
subjects:
- kind: ServiceAccount
    name: "{{ .Values.name }}"
    namespace: "{{ .Values.namespace }}"
roleRef:
    kind: Role
    name: "{{ .Values.name }}-role"
    apiGroup: rbac.authorization.k8s.io