# Schaema loaded also needs secrets to talk to Mongo & mySql, that means this job has to fetch the secrets from the vault, then only it can make the schema injection
{{ if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema-load
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.name }}
      initContainers:
      - name: config-init-from-vault
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/config-init-from-vault:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAME
            value: {{ .Values.name }}
          - name: ENVIRONMENT
            value: {{ .Values.environment }}
        envFrom: 
          - secretRef: 
              name: vault     
      containers:
      - name: {{ $.Values.name }}-schema-load
        image: public.ecr.aws/w2x3d9u7/roboshop-v3/schema-load
        env:
          - name: SCHEMA_FILE
            value: {{ $.Values.schema.schemaFiles }}
        envFrom: 
          - secretRef: 
              name: {{ .Values.name }}
{{ end }}
