# Schaema loaded also needs secrets to talk to MongoDB
# As MySQL Schema Injection Takes time we kept this out of schema jobs
{{ if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema-load
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.name }}
      initContainers:
      - name: config-init-from-vault
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/config-init-from-vault:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAME
            value: {{ .Values.name }}
          - name: ENVIRONMENT
            value: {{ .Values.environment }}
        envFrom: 
          - secretRef: 
              name: vault     
      containers:
      - name: {{ $.Values.name }}-schema-load
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/roboshop-schema-load
        env:
          - name: SCHEMA_FILE
            value: {{ $.Values.schema.schemaFiles }}
        envFrom: 
          - secretRef: 
              name: {{ $.Values.name }}
{{ end }}